version: '3.8'
services:
  express:
    image: giftr-api-w21
    container_name: giftr-api-w21
    environment:
      API_JWTKEY: 633gnm5o9xh02f594ila6wdblbu14c
      API_PORT: 80
      NODE_ENV: 'stage'
    ports:
      - 3030:80
    command: node server.js